CONFIG_ZMK_POINTING=y
CONFIG_ZMK_MOUSE=y

CONFIG_PMW3610_CPI=1200
CONFIG_ZMK_POINTING=y
CONFIG_ZMK_POINTING_ACCELERATION=y
CONFIG_ZMK_POINTING_ACCELERATION_EXPONENT=2
CONFIG_ZMK_POINTING_ACCELERATION_MULTIPLIER=3
#CONFIG_ZMK_POINTING_ACCELERATION=n
CONFIG_ZMK_POINTING_POLLING_INTERVAL=5
